### ISSUE TITLE
Access to the code of your paper

### ISSUE THREAD

**Issue by cintaracorp** [SirPryderi/space.fwd#2]
I found your paper, "A SOFTWARE PACKAGE TO SUPPORT MISSION ANALYSIS AND ORBITAL
MECHANICS CALCULATIONS", and was curious to get the source code for it, however the link on your home page (https://fenix.tecnico.ulisboa.pt/homepage/ist151699/simorbit) is broken. It seems that the paper's source was more complete than this javascript project. Would it be possible to create a github project for the paper's source code as well?

**Comment by SirPryderi** [comment]
Hello @cintaracorp,

Unfortunately I'm but a lowly developer and I haven't written any paper yet (maybe in the future!).

It looks like it's just a project with the same name.

> It seems that the paper's source was more complete than this javascript project.

Some offense taken! :P

Sorry I couldn't be of help, I wish you all the best in finding the other (more complete) SimOrbit!

**Comment by cintaracorp** [comment]
Oh! I am so sorry! I should have checked a bit deeper!
